### ISSUE TITLE
fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by ibrokemypie** [tanema/amore#10]
Hey, loving amore so far, however I seem to get random crashes while running that are not reproducible as they do not seem to have any particular cause.
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7f0e50fa0540]

runtime stack:
runtime.throw(0x55cae1efb72a, 0x2a)
	/usr/local/go/src/runtime/panic.go:566 +0x95
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x2cc

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x55cae1dfed30, 0xc420513848, 0x55ca00000000)
	/usr/local/go/src/runtime/cgocall.go:131 +0x110 fp=0xc4205137f0 sp=0xc4205137b0
github.com/go-gl/gl/v2.1/gl._Cfunc_glowBufferSubData(0x7f0e50454480, 0x8892, 0x0, 0x80, 0xc42728aa00)
	github.com/go-gl/gl/v2.1/gl/_obj/_cgo_gotypes.go:7543 +0x45 fp=0xc420513848 sp=0xc4205137f0
github.com/go-gl/gl/v2.1/gl.BufferSubData(0xc400008892, 0x0, 0x80, 0xc42728aa00)
	/home/conor/thingo/go/src/github.com/go-gl/gl/v2.1/gl/package.go:18284 +0x7c fp=0xc420513880 sp=0xc420513848
github.com/ibrokemypie/game/vendor/github.com/tanema/amore/gfx/gl.BufferSubData(0x55ca00008892, 0x0, 0x80, 0xc42728aa00)
	/home/conor/thingo/go/src/github.com/ibrokemypie/game/vendor/github.com/tanema/amore/gfx/gl/gl_opengl.go:134 +0x47 fp=0xc4205138b0 sp=0xc420513880
github.com/ibrokemypie/game/vendor/github.com/tanema/amore/gfx.(*vertexBuffer).bufferStatic(0xc4263fb780)
	/home/conor/thingo/go/src/github.com/ibrokemypie/game/vendor/github.com/tanema/amore/gfx/vertex_buffer.go:35 +0x8e fp=0xc4205138e0 sp=0xc4205138b0
github.com/ibrokemypie/game/vendor/github.com/tanema/amore/gfx.(*vertexBuffer).bufferData(0xc4263fb780)
	/home/conor/thingo/go/src/github.com/ibrokemypie/game/vendor/github.com/tanema/amore/gfx/vertex_buffer.go:67 +0xcd fp=0xc420513910 sp=0xc4205138e0
github.com/ibrokemypie/game/vendor/github.com/tanema/amore/gfx.(*vertexBuffer).fill(0xc4263fb780, 0x0, 0xc420513978, 0x20, 0x20)
	/home/conor/thingo/go/src/github.com/ibrokemypie/game/vendor/github.com/tanema/amore/gfx/vertex_buffer.go:99 +0x120 fp=0xc420513940 sp=0xc420513910
github.com/ibrokemypie/game/vendor/github.com/tanema/amore/gfx.(*SpriteBatch).addv(0xc4272862d0, 0xc420010740, 0x10, 0x10, 0xc4263fb7c0, 0xffffffffffffffff, 0x41c0000040b20000, 0x40b2000000000000)
	/home/conor/thingo/go/src/github.com/ibrokemypie/game/vendor/github.com/tanema/amore/gfx/sprite_batch.go:150 +0x24e fp=0xc420513a08 sp=0xc420513940
github.com/ibrokemypie/game/vendor/github.com/tanema/amore/gfx.(*SpriteBatch).Addq(0xc4272862d0, 0xc420012900, 0xc420513af8, 0x2, 0x2, 0xc42055ff80, 0x1)
	/home/conor/thingo/go/src/github.com/ibrokemypie/game/vendor/github.com/tanema/amore/gfx/sprite_batch.go:56 +0xa7 fp=0xc420513a70 sp=0xc420513a08
github.com/ibrokemypie/game/vendor/github.com/tanema/amore/gfx.(*Text).generate(0xc42355b140)
	/home/conor/thingo/go/src/github.com/ibrokemypie/game/vendor/github.com/tanema/amore/gfx/text.go:154 +0x3c4 fp=0xc420513c18 sp=0xc420513a70
github.com/ibrokemypie/game/vendor/github.com/tanema/amore/gfx.(*Text).loadVolatile(0xc42355b140, 0xc42661a9f8)
	/home/conor/thingo/go/src/github.com/ibrokemypie/game/vendor/github.com/tanema/amore/gfx/text.go:110 +0x129 fp=0xc420513c90 sp=0xc420513c18
github.com/ibrokemypie/game/vendor/github.com/tanema/amore/gfx.registerVolatile(0x55cae2242860, 0xc42355b140)
	/home/conor/thingo/go/src/github.com/ibrokemypie/game/vendor/github.com/tanema/amore/gfx/volatile.go:22 +0x8e fp=0xc420513ce8 sp=0xc420513c90
github.com/ibrokemypie/game/vendor/github.com/tanema/amore/gfx.NewColorTextExt(0xc420014280, 0xc42661aad0, 0x1, 0x1, 0xc425b75d68, 0x1, 0x1, 0xbf800000, 0x1, 0x3134323200000000, ...)
	/home/conor/thingo/go/src/github.com/ibrokemypie/game/vendor/github.com/tanema/amore/gfx/text.go:100 +0x1d0 fp=0xc420513d40 sp=0xc420513ce8
github.com/ibrokemypie/game/vendor/github.com/tanema/amore/gfx.NewTextExt(0xc420014280, 0xc42661a9f8, 0x4, 0xbf800000, 0x1, 0x0, 0x0, 0x0)
	/home/conor/thingo/go/src/github.com/ibrokemypie/game/vendor/github.com/tanema/amore/gfx/text.go:71 +0x1a2 fp=0xc420513dc8 sp=0xc420513d40
github.com/ibrokemypie/game/vendor/github.com/tanema/amore/gfx.NewText(0xc420014280, 0xc42661a9f8, 0x4, 0xa, 0xc42661a9f8, 0x4)
	/home/conor/thingo/go/src/github.com/ibrokemypie/game/vendor/github.com/tanema/amore/gfx/text.go:62 +0x56 fp=0xc420513e18 sp=0xc420513dc8
github.com/ibrokemypie/game/vendor/github.com/tanema/amore/gfx.Print(0xc42661a9f8, 0x4, 0xc420513e80, 0x2, 0x2)
	/home/conor/thingo/go/src/github.com/ibrokemypie/game/vendor/github.com/tanema/amore/gfx/text.go:24 +0x62 fp=0xc420513e58 sp=0xc420513e18
main.draw()
	/home/conor/thingo/go/src/github.com/ibrokemypie/game/main/game.go:30 +0x72 fp=0xc420513e98 sp=0xc420513e58
github.com/ibrokemypie/game/vendor/github.com/tanema/amore.Start(0x55cae1f15d80, 0x55cae1f15d70, 0x0, 0x0)
	/home/conor/thingo/go/src/github.com/ibrokemypie/game/vendor/github.com/tanema/amore/engine.go:49 +0x1ec fp=0xc420513f18 sp=0xc420513e98
main.main()
	/home/conor/thingo/go/src/github.com/ibrokemypie/game/main/game.go:21 +0x3e fp=0xc420513f48 sp=0xc420513f18
runtime.main()
	/usr/local/go/src/runtime/proc.go:183 +0x1f4 fp=0xc420513fa0 sp=0xc420513f48
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420513fa8 sp=0xc420513fa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1
```

**Comment by tanema** [comment]
Weird, do you have a snippet of what you are printing? Does the string change when you are printing?
